# Zambia Economic Analysis - Data Cleaning
This notebook focuses on loading, inspecting, and cleaning macroeconomic data including GDP, exchange rates, and copper prices.

In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
#Loading the dataset
df = pd.read_csv("C:/Users/user/Zambia_Economic_Analysis/data/raw/Zambia_Macro_Data.csv")
df.head()

,Year,GDP_Growth,Inflation,Debt_GDP,FDI_GDP,Population,Exchange_Rate,Copper_Price
0,1964,12.214048,NaN,NaN,NaN,3577017,0.714286,0.403233
1,1965,16.647456,NaN,NaN,NaN,3692086,0.714286,0.489251
2,1966,-5.570310,NaN,NaN,NaN,3812003,0.714286,0.633821
3,1967,7.919697,NaN,NaN,NaN,3936343,0.714286,0.491840
4,1968,1.248330,NaN,NaN,NaN,4065593,0.714286,0.507980

In [8]:
#understanding the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           61 non-null     int64
 1   GDP_Growth     61 non-null     float64
 2   Inflation      39 non-null     float64
 3   Debt_GDP       21 non-null     float64
 4   FDI_GDP        55 non-null     float64
 5   Population     61 non-null     int64
 6   Exchange_Rate  61 non-null     float64
 7   Copper_Price   61 non-null     float64
dtypes: float64(6), int64(2)
memory usage: 3.9 KB

In [6]:
df.describe()

,Year,GDP_Growth,Inflation,Debt_GDP,FDI_GDP,Population,Exchange_Rate,Copper_Price
count,61.000000,61.000000,39.000000,21.000000,55.000000,6.100000e+01,61.000000,61.000000
mean,1994.000000,3.454570,35.236352,105.348764,3.481361,9.928663e+06,3.870916,1.581366
std,17.752934,4.545495,42.950308,76.522391,2.664945,5.129237e+06,5.893351,1.199437
min,1964.000000,-8.625442,6.429397,17.321511,-0.958054,3.577017e+06,0.000643,0.403233
25%,1979.000000,-0.086040,10.383971,46.432894,1.362533,5.631728e+06,0.008266,0.668158
50%,1994.000000,3.897323,18.324440,71.411176,2.810624,8.576269e+06,0.714286,1.008752
75%,2009.000000,6.280749,39.001343,161.232158,5.033818,1.349039e+07,4.797500,2.721849
max,2024.000000,16.647456,183.312041,277.530308,9.604383,2.131496e+07,26.166419,4.244540

In [7]:
df.isnull().sum()

Year              0
GDP_Growth        0
Inflation        22
Debt_GDP         40
FDI_GDP           6
Population        0
Exchange_Rate     0
Copper_Price      0
dtype: int64

In [9]:
df = df.copy()

In [12]:
# Handling missing data
df['Inflation'] = df['Inflation'].interpolate(method='linear')
df['Debt_GDP'] = df['Debt_GDP'].interpolate(method='linear')
df['FDI_GDP'] =df['FDI_GDP'].interpolate()

In [13]:
# Creating new features
# Population growth
df['Population_Growth'] = df['Population'].pct_change() * 100

# Lag features
df['GDP_Lag'] = df['GDP_Growth'].shift(1)
df['Inflation_Lag'] = df['Inflation'].shift(1)

In [17]:
# Creating clean datasets
# Full dataset 
df_full = df.copy()
# ML dataset
df_ml = df[df['Year'] > 1990].copy()
df_ml = df_ml.dropna()
# debt_dataset
df_debt = df.dropna(subset=['Debt_GDP'])

In [16]:
df_ml.isnull().sum()

Year                 0
GDP_Growth           0
Inflation            0
Debt_GDP             0
FDI_GDP              0
Population           0
Exchange_Rate        0
Copper_Price         0
Population_Growth    0
GDP_Lag              0
Inflation_Lag        0
dtype: int64

In [20]:
# Final validation
print("Full Data Missing:\n", df_full.isnull().sum())
print("\nML Data Missing:\n", df_ml.isnull().sum())
print("\nDebt Data Missing:\n", df_debt.isnull().sum())

Full Data Missing:
 Year                  0
GDP_Growth            0
Inflation            22
Debt_GDP             26
FDI_GDP               6
Population            0
Exchange_Rate         0
Copper_Price          0
Population_Growth     1
GDP_Lag               1
Inflation_Lag        23
dtype: int64

ML Data Missing:
 Year                 0
GDP_Growth           0
Inflation            0
Debt_GDP             0
FDI_GDP              0
Population           0
Exchange_Rate        0
Copper_Price         0
Population_Growth    0
GDP_Lag              0
Inflation_Lag        0
dtype: int64

Debt Data Missing:
 Year                 0
GDP_Growth           0
Inflation            0
Debt_GDP             0
FDI_GDP              0
Population           0
Exchange_Rate        0
Copper_Price         0
Population_Growth    0
GDP_Lag              0
Inflation_Lag        0
dtype: int64

In [19]:
df_full.head()

,Year,GDP_Growth,Inflation,Debt_GDP,FDI_GDP,Population,Exchange_Rate,Copper_Price,Population_Growth,GDP_Lag,Inflation_Lag
0,1964,12.214048,NaN,NaN,NaN,3577017,0.714286,0.403233,NaN,NaN,NaN
1,1965,16.647456,NaN,NaN,NaN,3692086,0.714286,0.489251,3.216898,12.214048,NaN
2,1966,-5.570310,NaN,NaN,NaN,3812003,0.714286,0.633821,3.247947,16.647456,NaN
3,1967,7.919697,NaN,NaN,NaN,3936343,0.714286,0.491840,3.261802,-5.570310,NaN
4,1968,1.248330,NaN,NaN,NaN,4065593,0.714286,0.507980,3.283505,7.919697,NaN

In [23]:
df_full.to_csv("C:/Users/user/Zambia_Economic_Analysis/data/cleaned datasets/cleaned_full_data.csv", index=False)
df_ml.to_csv("C:/Users/user/Zambia_Economic_Analysis/data/cleaned datasets/cleaned_ml_data.csv", index=False)
df_debt.to_csv("C:/Users/user/Zambia_Economic_Analysis/data/cleaned datasets/debt_data.csv", index=False)